test_config:
  project: "swiftui-loop-videoplayer-example.xcodeproj"
  scheme: "swiftui-loop-videoplayer-example"
  destinations:
    - "platform=iOS Simulator,name=iPhone 15,OS=17.4"
    - "platform=iOS Simulator,name=iPhone 15 Plus,OS=17.4"
    - "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"
    - "platform=iOS Simulator,name=iPhone 15 Pro Max,OS=17.4"
